src/configurations/destinations/ga4_v2/ui-config.json
=> feat: use autoComplete in ga4v2

src/configurations/sources/braze/ui-config.json
The previous [PR](https://github.com/rudderlabs/rudder-integrations-config/pull/1518) got reverted due to some other revert. Hence raising it again
Resolves INT-2230
N/A
N/A
N/A
<hr>
=> feat: braze source event mapping

src/configurations/destinations/cordial/db-config.json, src/configurations/destinations/cordial/schema.json, src/configurations/destinations/cordial/ui-config.json, test/data/validation/destinations/cordial.json
Resolves INT-2386
N/A
N/A
N/A
<hr>
=> feat: onboard cordial destination

src/configurations/destinations/braze/ui-config.json
Add support for Shopify source for braze purchase events config
N/A
N/A
N/A
<hr>
=> chore: braze purchase events shopify

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/braze/ui-config.json, src/configurations/destinations/ga4/ui-config.json, src/configurations/destinations/ga4_v2/db-config.json, src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
=> chore(release): pull hotfix-release/v1.82.1 into main

src/configurations/destinations/ga4_v2/db-config.json, src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
Enable back the override client_id and session_id config for ga4 v2
Resolves INT-2444
N/A
N/A
N/A
<hr>
=> chore: enable override flag to ga4 v2 ui configs

src/configurations/destinations/ga4_v2/db-config.json, src/configurations/destinations/ga4_v2/schema.json, src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt, test/data/validation/destinations/ga4_v2.json
=> fix: ga4 v2 config

src/configurations/destinations/google_adwords_remarketing_lists/db-config.json
=> chore: enable record event for GARL

src/configurations/destinations/azure_datalake/ui-config.json, src/configurations/destinations/azure_synapse/ui-config.json, src/configurations/destinations/bq/ui-config.json, src/configurations/destinations/deltalake/ui-config.json, src/configurations/destinations/gcs_datalake/ui-config.json, src/configurations/destinations/mssql/ui-config.json, src/configurations/destinations/postgres/ui-config.json, src/configurations/destinations/rs/ui-config.json, src/configurations/destinations/s3_datalake/ui-config.json, src/configurations/destinations/snowflake/ui-config.json
Add immutable property to namespace field in uiConfig of destinations using old form builder
Completes OBS-589
We don't want to give option to user to edit namespace once destination is created
N/A
N/A
N/A
<hr>
=> chore: add immutable property to namespace field

src/configurations/sources/redshift/schema.json, src/configurations/sources/redshift/ui-config.json
Part of REV-1151
N/A
N/A
N/A
<hr>
=> feat: iam support for redshift source

src/configurations/sources/singer_facebook_marketing/db-config.json
Updated image version for facebook singer (version upgrade of facebook marketing)
=> chore: facebook version upgrade

CHANGELOG.md, package-lock.json, package.json, src/configurations/sources/singer_facebook_marketing/db-config.json
=> chore(release): pull hotfix-release/v1.86.1 into main

src/configurations/destinations/sfmc/db-config.json
We are onboarding sfmc with VDM.
Resolves INT-1828
N/A
N/A
N/A
<hr>
=> feat: enable vdm for sfmc

src/configurations/destinations/smartly/db-config.json, src/configurations/destinations/smartly/schema.json, src/configurations/destinations/smartly/ui-config.json, test/data/validation/destinations/smartly.json
Onboard Smartly destination
Resolves INT-1515
- Screenshot of UI:
N/A
N/A
N/A
<hr>
=> feat: onboard smartly destination

src/configurations/destinations/snapchat_conversion/db-config.json
Snapchat custom audience were not being able to be connected with an audience source
Resolves RUD-2052
N/A
N/A
N/A
<hr>
=> fix: snapchat custom audience support

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/ga4_v2/db-config.json, src/configurations/destinations/snapchat_conversion/db-config.json
=> chore(release): pull hotfix-release/v1.87.1 into main

src/configurations/destinations/snapchat_conversion/db-config.json, src/configurations/destinations/snapchat_custom_audience/db-config.json
Resolves RUD-2052
N/A
N/A
N/A
<hr>
=> fix: remove wrong conf from snapchat conversion and add for custom aud

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/snapchat_conversion/db-config.json, src/configurations/destinations/snapchat_custom_audience/db-config.json
=> chore(release): pull hotfix-release/v1.87.2 into main

src/configurations/destinations/sfmc/db-config.json
We are adding support of retl audience to sfmc.
Resolves INT-1828
N/A
N/A
N/A
<hr>
=> feat: add audience support for sfmc destination

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/sfmc/db-config.json
=> chore(release): pull hotfix-release/v1.88.0 into main

package-lock.json
ran npm audit fix
Resolves INT-2593
N/A
N/A
N/A
<hr>
=> fix: npm vulnerabilities

src/configurations/destinations/facebook_pixel/ui-config.json, src/configurations/destinations/fullstory/ui-config.json, src/configurations/destinations/ga4/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/iterable/ui-config.json, src/configurations/destinations/ninetailed/ui-config.json, src/configurations/destinations/optimizely_fullstack/ui-config.json, src/configurations/destinations/sprig/ui-config.json
Replaced connectionModes.cloud with respective source type specific fields
Resolves INT-2319
N/A
N/A
N/A
<hr>
=> feat: replaced connectionModes.cloud with respective source type specific fields

src/configurations/destinations/am/ui-config.json, src/configurations/destinations/fullstory/ui-config.json, src/configurations/destinations/intercom/ui-config.json, src/configurations/destinations/rockerbox/ui-config.json, src/configurations/destinations/spotifyPixel/ui-config.json
Deprecate connectionModes.mobileDevice and connectionModes.webDevice keys
Resolves INT-2321
N/A
N/A
N/A
<hr>
=> feat: deprecate connectionModes.mobileDevice and connectionModes.webDevice keys

src/configurations/sources/singer_facebook_marketing/db-config.json
Update image for singer FB marketing to v8.3.4
The image has a change to raise an alert if the access_token is about to expire. 
N/A
N/A
N/A
<hr>
=> chore: update singer-fb-marketing image to v8.3.4

src/configurations/destinations/webhook_v2/db-config.json
=> chore: rename Webhook v2 destination to HTTP

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/webhook_v2/db-config.json
=> chore(release): pull hotfix-release/v1.90.1 into main

src/configurations/destinations/fb_custom_audience/db-config.json, src/configurations/destinations/fb_custom_audience/schema.json, src/configurations/destinations/fb_custom_audience/ui-config.json, test/data/validation/destinations/fb_custom_audience.json
Rearranged config fields to enhance UX in VDMv2
Resolves INT-2609
N/A
N/A
N/A
<hr>
=> feat: rearranged config fields to enhance UX

src/configurations/destinations/fb_custom_audience/db-config.json
=> chore: fix lint issue in FBCA

src/configurations/destinations/http/db-config.json, src/configurations/destinations/http/schema.json, src/configurations/destinations/http/ui-config.json, test/data/validation/destinations/http.json
Resolves INT-2618
N/A
N/A
N/A
<hr>
=> refactor: rename webhook v2 destination to http

src/configurations/destinations/x_audience/db-config.json, src/configurations/destinations/x_audience/schema.json, src/configurations/destinations/x_audience/ui-config.json, test/data/validation/destinations/x_audience.json
Onboarding new destination x(twitter) audience.
Supports only record type of event and cloud and warehouse mode of connections
Supports Mirror Mode and Oauth as well
Supports VDM and Blank Audience Creation as well
Screenshots:
Resolves INT-911
N/A
N/A
N/A
<hr>
=> feat: onboard X(Twiiter) Audience

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/iterable/schema.json
=> chore(release): pull hotfix-release/v1.90.2 into main

src/configurations/destinations/mp/ui-config.json
Resolves INT-2635
N/A
N/A
N/A
<hr>
=> fix: rename mixpanel api token to project token

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/mp/ui-config.json
=> chore(release): pull hotfix-release/v1.90.3 into main

src/configurations/destinations/fb_custom_audience/db-config.json, src/configurations/destinations/fb_custom_audience/schema.json, src/configurations/destinations/fb_custom_audience/ui-config.json, test/data/validation/destinations/fb_custom_audience.json
Resolves INT-2626
N/A
N/A
N/A
<hr>
=> feat(fb_custom_audience): move FBCA to form builder v2

src/configurations/destinations/http/db-config.json
=> chore: hide http destination

src/configurations/destinations/lytics_bulk_upload/db-config.json, src/configurations/destinations/lytics_bulk_upload/schema.json
Resolves INT- 1984
N/A
N/A
N/A
<hr>
=> feat: adding cloud source and web source for lytics bulk

src/configurations/destinations/fb_custom_audience/ui-config.json
=> chore(fb_custom_audience): update placeholders with e.g:

src/configurations/destinations/fb_custom_audience/ui-config.json
=> chore(fb_custom_audience): replace name with label in options in ui-config fields

src/configurations/sources/http/schema.json
=> chore(HTTP source): update HTTP source schema to empty object from null

src/configurations/destinations/wunderkind/ui-config.json
Resolves RUD-2110
N/A
N/A
N/A
<hr>
=> fix: set wunderkind accountId and instanceId as secret in ui

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/kafka/ui-config.json, src/configurations/destinations/wunderkind/ui-config.json, test/data/validation/destinations/kafka.json
:crown: *An automated PR*
Resovles INT-2685
=> chore(release): pull hotfix-release/v1.92.1 into main

src/configurations/destinations/fb_custom_audience/ui-config.json
Hide particular fields from ui config when VDMv2 is enabled
N/A
N/A
N/A
<hr>
=> feat(fb_custom_audience): hide particular fields from ui config when VDMv2 is enabled

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/fb_custom_audience/ui-config.json
=> chore(release): pull hotfix-release/v1.93.0 into main

src/configurations/sources/singer_google_ads/db-config.json
=> chore: update google ads image to v8.3.6

src/configurations/sources/singer_shopify/db-config.json
=> chore: update shopify image to v8.3.7

src/configurations/destinations/singular/ui-config.json
remove feature flag for singular config for general release
N/A
N/A
N/A
<hr>
=> chore: remove feature flag for singular config for general release

src/configurations/destinations/mp/schema.json, src/configurations/destinations/mp/ui-config.json
Resolves INT-2723
N/A
N/A
N/A
<hr>
=> feat: hide mixpanel service account settings

src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
Update ui-config.jt file to reflect consent management changes
N/A
N/A
N/A
<hr>
=> fix(ga4_v2): update ui-config.jt file to reflect consent management changes

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
=> chore(release): pull hotfix-release/v1.93.1 into main

src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
=> chore(ga4v2): rearrange sections

src/configurations/destinations/ga4_v2/ui-config.json, src/configurations/destinations/ga4_v2/ui-config.jt
Reverts rudderlabs/rudder-integrations-config#1724
=> Revert "chore(ga4v2): rearrange sections"

src/configurations/destinations/bq/db-config.json, src/configurations/destinations/bq/schema.json, src/configurations/destinations/bq/ui-config.json, src/configurations/destinations/rs/db-config.json, src/configurations/destinations/rs/schema.json, src/configurations/destinations/rs/ui-config.json, test/data/validation/destinations/bq.json, test/data/validation/destinations/rs.json
- It introduces the changes back again for: 
- https://github.com/rudderlabs/rudder-integrations-config/pull/1710
- https://github.com/rudderlabs/rudder-integrations-config/pull/1630
=> fix: redshift serverless bq partitioning configuration changes

src/configurations/sources/singer_zendesk_support/db-config.json
=> fix: update image for singer zendesk support to v8.3.9

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/sprig/db-config.json, src/configurations/destinations/sprig/schema.json, src/configurations/destinations/sprig/ui-config.json, test/data/validation/destinations/sprig.json
=> chore(release): pull hotfix-release/v1.96.0 into main

src/configurations/destinations/mp/ui-config.json
=> chore: mixpanel ui config var name change

src/configurations/destinations/tune/db-config.json
Adding feature flag to add Tune destination.
N/A
N/A
N/A
<hr>
=> feat: feature flag to hide tune dest

src/configurations/destinations/tune/db-config.json, src/configurations/destinations/tune/schema.json, src/configurations/destinations/tune/ui-config.json, test/data/validation/destinations/tune.json
Updated Tune Ui as per the requirements
Resolves INT-282
Ui:
N/A
N/A
N/A
<hr>
=> fix: updated tune ui

src/configurations/destinations/mp/ui-config.json
=> chore: added default value for sessionReplayPercentage in MP

src/configurations/sources/singer_klaviyo_v2/db-config.json
=> chore: update klaviyo image to v8.3.12

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/bq/schema.json, src/configurations/destinations/bq/ui-config.json, test/data/validation/destinations/bq.json
=> chore(release): pull hotfix-release/v1.97.3 into main

src/configurations/sources/singer_shopify/db-config.json
=> chore: update shopify  image to v8.3.13

src/configurations/destinations/intercom_v2/db-config.json
=> chore: removing intercom vdm-next

src/configurations/destinations/google_adwords_remarketing_lists/ui-config.json
Add VDMv2 related prerequisite checks to GARL
Resolves INT-2881
N/A
N/A
N/A
<hr>
=> feat: add VDMv2 related prerequisite checks to GARL

src/configurations/destinations/tiktok_ads/db-config.json, src/configurations/destinations/tiktok_ads/schema.json
Adding shopify source to tiktok ads
Resolves INT-2891
N/A
N/A
N/A
<hr>
=> feat: adding shopify source to tiktok ads

src/configurations/destinations/linkedin_audience/db-config.json
We are adding a feature flag to disable this destination on production by default.
N/A
N/A
N/A
<hr>
=> chore: add feature flag to hide on linkedin audience

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/linkedin_audience/db-config.json
=> chore(release): pull hotfix-release/v1.98.1 into main

src/configurations/destinations/topsort/db-config.json, src/configurations/destinations/topsort/schema.json, src/configurations/destinations/topsort/ui-config.json, test/data/validation/destinations/topsort.json
We are onboarding a new destination named topsort.
N/A
N/A
N/A
<hr>
=> feat: onboard topsort destination (#1842)

src/configurations/sources/javascript/db-config.json
I renamed the display name of JavaScript source to the correct value.
https://linear.app/rudderstack/issue/SDK-2767/rename-cloud-to-server-side-sources-or-anything-appropriate-in-the
I've fixed an issue with the display name that was pending for a long time.
N/A
N/A
N/A
<hr>
=> fix: javascript source display name

src/configurations/destinations/mp/db-config.json, src/configurations/destinations/mp/schema.json, src/configurations/destinations/mp/ui-config.json, test/data/validation/destinations/mp.json
…1870)"
This reverts commit 474cde545d8d2786e49dfe18ef656209e1c31b67.
Resolves INT-3168
N/A
N/A
N/A
<hr>
=> revert:  feat added drop traits in track call feature for mixpanel

src/configurations/destinations/http/db-config.json
Add missing key definition in db-config
Resolves INT-3212
N/A
N/A
N/A
<hr>
=> fix(http): add missing key definition in db-config

src/configurations/destinations/moengage/schema.json
=> chore: add connection mode in schema json for moengage (#1929)

.github/workflows/deploy-to-dev.yml, CHANGELOG.md, package-lock.json, package.json, scripts/schemaGenerator.py, src/configurations/destinations/deltalake/db-config.json, src/configurations/destinations/deltalake/schema.json, src/configurations/destinations/deltalake/ui-config.json, src/configurations/destinations/moengage/db-config.json, src/configurations/destinations/moengage/schema.json, src/configurations/destinations/moengage/ui-config.json, src/configurations/destinations/zoho/ui-config.json, src/configurations/sources/facebook_lead_ads/db-config.json, src/configurations/sources/facebook_lead_ads/schema.json, src/configurations/sources/facebook_lead_ads/ui-config.json, src/configurations/sources/shopify/ui-config.json, test/data/validation/destinations/deltalake.json, test/data/validation/destinations/moengage.json
=> chore(release): pull release/v1.107.0 into main

src/configurations/destinations/klaviyo_bulk_upload/db-config.json
Resolves INT-3318
N/A
N/A
N/A
<hr>
=> feat: disable json mapper in klaviyo bulk upload destination

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/klaviyo_bulk_upload/db-config.json
=> chore(release): pull hotfix-release/v1.108.0 into main

.github/workflows/create-hotfix-branch.yml, CHANGELOG.md, package-lock.json, package.json, src/configurations/sources/snowflake/ui-config.json
=> chore(release): pull hotfix-release/v1.109.1 into main

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/hs/schema.json, src/configurations/destinations/hs/ui-config.json, src/configurations/destinations/klaviyo_bulk_upload/db-config.json, src/configurations/destinations/klaviyo_bulk_upload/ui-config.json, src/configurations/destinations/tiktok_ads/schema.json, src/configurations/destinations/tiktok_ads/ui-config.json, src/configurations/sources/singer_google_ads/db-config.json
=> chore(release): pull release/v1.112.0 into main

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/azure_datalake/ui-config.json, src/configurations/destinations/azure_synapse/ui-config.json, src/configurations/destinations/bq/db-config.json, src/configurations/destinations/bq/schema.json, src/configurations/destinations/bq/ui-config.json, src/configurations/destinations/clickhouse/ui-config.json, src/configurations/destinations/deltalake/ui-config.json, src/configurations/destinations/gcs_datalake/ui-config.json, src/configurations/destinations/http/db-config.json, src/configurations/destinations/mssql/ui-config.json, src/configurations/destinations/postgres/ui-config.json, src/configurations/destinations/rs/ui-config.json, src/configurations/destinations/s3_datalake/ui-config.json, src/configurations/destinations/snowflake/ui-config.json, src/configurations/destinations/snowpipe_streaming/ui-config.json, test/data/validation/destinations/bq.json
=> chore(release): pull hotfix-release/v1.112.1 into main

src/configurations/destinations/braze/db-config.json, src/configurations/destinations/intercom/db-config.json, src/configurations/destinations/intercom_v2/db-config.json
Updated for braze, intercom and intercom v2 destinations
Resolves INT-3504
N/A
N/A
N/A
<hr>
=> chore: update throttling cost limtis

CHANGELOG.md, package-lock.json, package.json, src/configurations/sources/bigquery/db-config.json, src/configurations/sources/databricks/db-config.json, src/configurations/sources/mysql/db-config.json, src/configurations/sources/postgres/db-config.json, src/configurations/sources/redshift/db-config.json, src/configurations/sources/snowflake/db-config.json, src/configurations/sources/trino/db-config.json, src/schemas/sources/db-config-schema.json
=> chore(release): pull hotfix-release/v1.113.2 into main

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/tiktok_ads/schema.json, src/configurations/destinations/tiktok_ads/ui-config.json
=> chore(release): pull hotfix-release/v1.113.3 into main

src/configurations/destinations/zoho_dev/db-config.json
Hide zoho_dev destination from prod.
N/A
N/A
N/A
<hr>
=> chore: hide zoho dev from prod

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/zoho_dev/db-config.json
=> chore(release): pull hotfix-release/v1.114.1 into main

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/sftp/db-config.json, src/schemas/destinations/db-config-schema.json
=> chore(release): pull hotfix-release/v1.114.2 into main

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/gainsight_px/db-config.json, src/configurations/destinations/gainsight_px/schema.json, test/data/validation/destinations/gainsight_px.json
=> chore(release): pull release/v1.114.3 into main

src/configurations/destinations/klaviyo/db-config.json
This pull request includes minor updates to versioning and documentation, as well as a configuration enhancement for Klaviyo destinations.
* [`src/configurations/destinations/klaviyo/db-config.json`](diffhunk://#diff-5e19de1705bbada0958072b009e919570016b49cc085eacab3ad3e6ffe2ea19aR63): Added a new configuration option, `useNewKlaviyoRevisionVersion`, to the Klaviyo destination settings.
Resolves INT-3737
N/A
N/A
N/A
<hr>
=> chore: add klaviyo october version boolean config

scripts/deployToDB.py
doing case insensitive matching with blacklist
Resolves INT-3746
only blacklist changed
N/A
N/A
<hr>
=> chore: fix blacklisted destination matching

src/configurations/destinations/criteo_audience/db-config.json, src/configurations/destinations/criteo_audience/schema.json, src/configurations/destinations/criteo_audience/ui-config.json, test/data/validation/destinations/criteo_audience.json
=> fix: criteo audience incorrect schema (#2044)

CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/attentive_tag/schema.json, src/configurations/destinations/attentive_tag/ui-config.json, src/configurations/destinations/criteo_audience/db-config.json, src/configurations/destinations/criteo_audience/schema.json, src/configurations/destinations/criteo_audience/ui-config.json, test/data/validation/destinations/attentive_tag.json, test/data/validation/destinations/criteo_audience.json
=> chore(release): pull hotfix-release/v1.116.1 into main

src/configurations/destinations/postgres/schema.json, src/configurations/destinations/postgres/ui-config.json
Reverts rudderlabs/rudder-integrations-config#2062
=> Revert "fix: increase length limit for host in postgres destination"

src/configurations/destinations/tiktok_ads/schema.json, src/configurations/destinations/tiktok_ads/ui-config.json
Reverts rudderlabs/rudder-integrations-config#2071
=> Revert "feat: add new mapping for tiktok ads"

src/configurations/destinations/postscript/db-config.json
Update feature flag name for postscript
N/A
N/A
N/A
<hr>
=> chore: update feature flag name for postscript

scripts/constants.py
Increasing the timeout from 10 sec to 30 sec to pass the deployment workflow. 
Resolves INT-3913
N/A
N/A
N/A
<hr>
=> chore: increase timeout for http client

CHANGELOG.md, package-lock.json, package.json, scripts/constants.py, src/configurations/sources/singer_facebook_marketing/db-config.json
=> chore(release): pull hotfix-release/v1.118.1 into main

src/configurations/sources/singer_facebook_marketing/db-config.json
=> fix: update fb markeing image to v8.3.19

.github/workflows/deploy.yml, .github/workflows/publish-new-release.yml, CHANGELOG.md, package-lock.json, package.json, src/configurations/destinations/google_adwords_enhanced_conversions/accounts/google_adwords_enhanced_conversions_oauth/db-config.json, src/configurations/destinations/google_adwords_enhanced_conversions/accounts/google_adwords_enhanced_conversions_oauth/schema.json, src/configurations/destinations/google_adwords_enhanced_conversions/accounts/google_adwords_enhanced_conversions_oauth/ui-config.json, src/configurations/destinations/google_adwords_enhanced_conversions/db-config.json, src/configurations/destinations/google_adwords_offline_conversions/accounts/google_adwords_offline_conversions_oauth/db-config.json, src/configurations/destinations/google_adwords_offline_conversions/accounts/google_adwords_offline_conversions_oauth/schema.json, src/configurations/destinations/google_adwords_offline_conversions/accounts/google_adwords_offline_conversions_oauth/ui-config.json, src/configurations/destinations/google_adwords_offline_conversions/db-config.json, src/configurations/destinations/google_adwords_remarketing_lists/accounts/google_adwords_remarketing_lists_oauth/db-config.json, src/configurations/destinations/google_adwords_remarketing_lists/accounts/google_adwords_remarketing_lists_oauth/schema.json, src/configurations/destinations/google_adwords_remarketing_lists/accounts/google_adwords_remarketing_lists_oauth/ui-config.json, src/configurations/destinations/google_adwords_remarketing_lists/db-config.json, src/configurations/destinations/klaviyo/db-config.json, src/configurations/destinations/salesforce/db-config.json, src/configurations/destinations/salesforce_oauth/accounts/salesforce_oauth/schema.json, src/configurations/destinations/zoho/accounts/zoho_oauth/schema.json
=> chore(release): pull release/v1.124.0 into main

CHANGELOG.md, package-lock.json, package.json, scripts/schemaGenerator.py, src/configurations/destinations/dub/db-config.json, src/configurations/destinations/dub/schema.json, src/configurations/destinations/dub/ui-config.json, test/component_tests/data/createNewSchemaDest.json, test/component_tests/data/createNewSchemaDestLegacyUI.json, test/component_tests/data/updateSchemaDest.json, test/component_tests/data/updateSchemaDestLegacyUI.json, test/component_tests/schemaGenerator.test.ts, test/data/validation/destinations/dub.json
=> chore(release): pull hotfix-release/v1.129.0 into main
